apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: ajdfhakjdfh
  annotations:
    github.com/project-slug: cds-snc/sentinel-workbook-test
    backstage.io/techdocs-ref: dir:.
spec:
  type: website 
  lifecycle: production
  owner: group:cds-snc/internal-sre